# Generated by Django 5.0.4 on 2024-04-30 17:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="attendees",
        ),
        migrations.RemoveField(
            model_name="eventsuggestion",
            name="duration_10hr",
        ),
        migrations.RemoveField(
            model_name="eventsuggestion",
            name="duration_11hr",
        ),
        migrations.RemoveField(
            model_name="eventsuggestion",
            name="duration_12hr",
        ),
        migrations.RemoveField(
            model_name="eventsuggestion",
            name="duration_9hr",
        ),
        migrations.RemoveField(
            model_name="eventsuggestion",
            name="moday_early_morning",
        ),
        migrations.RemoveField(
            model_name="hobby",
            name="max_participants",
        ),
        migrations.AddField(
            model_name="onboarding",
            name="pronouns",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="scenarios",
            name="duration_h1",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(8),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="scenarios",
            name="duration_h2",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(8),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="duration_h",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(8),
                    django.core.validators.MinValueValidator(1),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="hobbytype",
            name="type",
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name="SuggestionResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_date", models.DateTimeField()),
                (
                    "probability_of_attendance",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="s2s.event"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_rating",
                    models.CharField(
                        choices=[
                            ("Not Rated", "Not Rated"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                        ]
                    ),
                ),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="s2s.event"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
