# Generated by Django 5.0.4 on 2024-05-03 21:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_picture",
        ),
    ]
