# Generated by Django 5.0.4 on 2024-05-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboarding",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="onboarding",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
