# Generated by Django 5.0.4 on 2024-05-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userevents",
            name="attended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userevents",
            name="rsvp",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], default="No", max_length=3
            ),
        ),
    ]
