# Generated by Django 5.0.4 on 2024-04-24 01:50

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "token",
                    models.CharField(
                        default=secrets.token_urlsafe, max_length=255, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
