# Generated by Django 5.0.4 on 2024-05-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0002_alter_userevents_user_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userevents",
            name="user_rating",
            field=models.CharField(
                choices=[
                    ("Did not attend", "Did not attend"),
                    ("Not Rated", "Not Rated"),
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                ],
                default="Not Rated",
                max_length=15,
            ),
        ),
    ]
