# Generated by Django 5.0.4 on 2024-05-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0002_remove_profile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="default_profile.jpeg", upload_to="profiles/"
            ),
        ),
    ]
