# Generated by Django 5.0.4 on 2024-04-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0002_applicationtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboarding",
            name="onboarded",
            field=models.BooleanField(default=False),
        ),
    ]
