# Generated by Django 5.0.4 on 2024-05-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0002_userevents_attended_userevents_rsvp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userevents",
            name="rsvp",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=3,
                null=True,
            ),
        ),
    ]
