# Generated by Django 5.0.4 on 2024-05-16 00:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0002_alter_userevents_user_rating 2"),
        ("s2s", "0003_alter_userevents_user_rating 2"),
        ("s2s", "0003_alter_userevents_user_rating"),
    ]

    operations = []
