# Generated by Django 5.0.4 on 2024-05-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "s2s",
            "0003_rename_hobby_category_art_eventsuggestion_hobby_category_arts_and_culture_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsuggestion",
            name="pref_hobby_category_arts_and_culture",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventsuggestion",
            name="pref_hobby_category_community",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventsuggestion",
            name="pref_hobby_category_cooking_and_baking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventsuggestion",
            name="pref_hobby_category_crafting",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventsuggestion",
            name="pref_hobby_category_exercise",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventsuggestion",
            name="pref_hobby_category_food",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventsuggestion",
            name="pref_hobby_category_gaming",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventsuggestion",
            name="pref_hobby_category_history",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventsuggestion",
            name="pref_hobby_category_literature",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventsuggestion",
            name="pref_hobby_category_outdoor_activities",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventsuggestion",
            name="pref_hobby_category_travel",
            field=models.BooleanField(default=False),
        ),
    ]
