# Generated by Django 5.0.4 on 2024-05-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s2s', '0004_merge_20240516_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userevents',
            name='user_rating',
            field=models.CharField(choices=[('Did not attend', 'Did not attend'), ('Not Rated', 'Not Rated'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Not Rated', max_length=15),
        ),
    ]
