# Generated by Django 5.0.4 on 2024-05-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0005_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.URLField(
                default="https://s2s-profile-photos.s3.amazonaws.com/https://s2s-profile-photos.s3.amazonaws.com/default_profile.jpeg"
            ),
        ),
    ]
