# Generated by Django 5.0.4 on 2024-05-04 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0006_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="event_id",
        ),
        migrations.AlterField(
            model_name="event",
            name="max_attendees",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(50),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.URLField(
                default="https://s2s-profile-photos.s3.amazonaws.com/default_profile.jpeg"
            ),
        ),
    ]
