# Generated by Django 5.0.4 on 2024-04-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0006_alter_onboarding_age_alter_onboarding_distance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboarding",
            name="leastInterestedIn",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="onboarding",
            name="mostInterestedIn",
            field=models.CharField(blank=True, null=True),
        ),
    ]
