# Generated by Django 5.0.4 on 2024-04-26 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0007_onboarding_leastinterestedin_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="onboarding",
            old_name="leastInterestedIn",
            new_name="least_interested_hobbies",
        ),
        migrations.RenameField(
            model_name="onboarding",
            old_name="mostInterestedIn",
            new_name="most_interested_hobbies",
        ),
    ]
