# Generated by Django 5.0.4 on 2024-05-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0007_remove_event_event_id_alter_event_max_attendees_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="address",
            new_name="address1",
        ),
        migrations.AddField(
            model_name="event",
            name="address2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="city",
            field=models.CharField(default="Chicago", max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="state",
            field=models.CharField(default="IL", max_length=100),
        ),
    ]
