# Generated by Django 5.0.4 on 2024-05-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0008_rename_address_event_address1_event_address2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
