# Generated by Django 5.0.4 on 2024-05-06 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0009_event_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="HobbyType",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="s2s.hobbytype",
            ),
        ),
    ]
