# Generated by Django 5.0.4 on 2024-04-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0012_alter_onboarding_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboarding",
            name="gender",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="race",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
