# Generated by Django 5.0.4 on 2024-05-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0012_alter_userevents_user_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="zipcode",
            field=models.CharField(default="60607", max_length=10),
        ),
    ]
