# Generated by Django 5.0.4 on 2024-05-07 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0013_event_zipcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="availability",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ],
                default="Monday",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="availability",
            name="hour",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(24),
                ],
            ),
        ),
    ]
