# Generated by Django 5.0.4 on 2024-05-07 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s2s', '0013_event_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsuggestion',
            name='event_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='s2s.event'),
            preserve_default=False,
        ),
    ]
