# Generated by Django 5.0.4 on 2024-05-07 22:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0014_panelevent_panelscenario_paneluserpreferences"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="panelevent",
            name="dist_within_10mi",
        ),
        migrations.RemoveField(
            model_name="panelevent",
            name="dist_within_15mi",
        ),
        migrations.RemoveField(
            model_name="panelevent",
            name="dist_within_1mi",
        ),
        migrations.RemoveField(
            model_name="panelevent",
            name="dist_within_20mi",
        ),
        migrations.RemoveField(
            model_name="panelevent",
            name="dist_within_30mi",
        ),
        migrations.RemoveField(
            model_name="panelevent",
            name="dist_within_40mi",
        ),
        migrations.RemoveField(
            model_name="panelevent",
            name="dist_within_50mi",
        ),
        migrations.RemoveField(
            model_name="panelevent",
            name="dist_within_5mi",
        ),
    ]
