# Generated by Django 5.0.4 on 2024-04-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0015_onboarding_address_line1_onboarding_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboarding",
            name="event_notification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Email Only", "Email Only"),
                    ("Text Only", "Text Only"),
                    ("Email and Text", "Email and Text"),
                    ("None", "None"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
