# Generated by Django 5.0.4 on 2024-05-08 00:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0015_alter_availability_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Calendar",
        ),
    ]
