# Generated by Django 5.0.4 on 2024-05-07 23:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0016_panelevent_event_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventSuggestion",
        ),
    ]
