# Generated by Django 5.0.4 on 2024-05-10 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0016_delete_calendar"),
        ("s2s", "0017_delete_eventsuggestion"),
    ]

    operations = []
