# Generated by Django 5.0.4 on 2024-05-14 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0018_merge_20240510_1855"),
        ("s2s", "0018_merge_20240514_0214"),
    ]

    operations = []
