# Generated by Django 5.0.4 on 2024-05-18 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("s2s", "0004_merge_20240516_0054"),
        ("s2s", "0019_merge_20240514_1603"),
    ]

    operations = []
