# Generated by Django 5.0.3 on 2024-03-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("18-24", "18 to 24"),
                            ("25-34", "25 to 34"),
                            ("35-44", "35 to 44"),
                            ("45-54", "45 to 54"),
                            ("55-64", "55 to 64"),
                            ("65-74", "65 to 74"),
                            ("75+", "75 and up"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
