# Generated by Django 5.0.4 on 2024-04-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0002_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="onboarded",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
