# Generated by Django 5.0.3 on 2024-04-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0002_hobby_scenario_format_alter_hobby_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age_range", models.CharField()),
                ("race_ethnicity", models.CharField()),
                ("gender", models.CharField()),
                ("sexual_orientation", models.CharField()),
                ("politics", models.CharField()),
                ("religion", models.CharField()),
                ("distance", models.CharField()),
                ("group_size", models.CharField()),
                ("similarity_metric", models.CharField()),
                ("similarity_attribute", models.CharField()),
                ("event_frequency", models.CharField()),
                ("notification_method", models.CharField()),
                ("time_of_day", models.CharField()),
            ],
        ),
    ]
