# Generated by Django 5.0.4 on 2024-04-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0003_onboarding_onboarded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboarding",
            name="age",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="distance",
            field=models.CharField(
                choices=[
                    (0, "Within 1 mile"),
                    (1, "Within 5 miles"),
                    (2, "Within 10 miles"),
                    (3, "Within 15 miles"),
                    (4, "Within 20 miles"),
                    (5, "Within 30 miles"),
                    (6, "Within 40 miles"),
                    (7, "Within 50 miles"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="gender",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="gender_description",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="num_participants",
            field=models.CharField(
                choices=[(0, "1-5"), (1, "5-10"), (2, "10-15"), (3, "15+")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="political_description",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="political_leaning",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="race",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="race_description",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="religion",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="religion_description",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="sexual_orientation_description",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="similarity_metrics",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="similarity_to_group",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True
            ),
        ),
    ]
