# Generated by Django 5.0.4 on 2024-04-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "s2s",
            "0008_rename_leastinterestedin_onboarding_least_interested_hobbies_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboarding",
            name="sexual_orientation",
            field=models.CharField(blank=True, null=True),
        ),
    ]
