# Generated by Django 5.0.4 on 2024-04-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s2s", "0013_alter_onboarding_gender_alter_onboarding_race"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboarding",
            name="distance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Within 1 mile", "Within 1 mile"),
                    ("Within 5 miles", "Within 5 miles"),
                    ("Within 10 miles", "Within 10 miles"),
                    ("Within 15 miles", "Within 15 miles"),
                    ("Within 20 miles", "Within 20 miles"),
                    ("Within 30 miles", "Within 30 miles"),
                    ("Within 40 miles", "Within 40 miles"),
                    ("Within 50 miles", "Within 50 miles"),
                    ("No preference", "No preference"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="num_participants",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1-5", "1-5"),
                    ("5-10", "5-10"),
                    ("10-15", "10-15"),
                    ("15+", "15+"),
                    ("No preference", "No preference"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
