export interface Onboarding {
    user_id: number,
    onboarded: boolean,
    num_participants: string,
    distance: string,
    similarity_to_group: string,
    similarity_metrics: string,
    gender: string,
    gender_description: string,
    race: string,
    race_description: string,
    age: string,
    sexual_orientation: string,
    sexual_orientation_description: string,
    religion: string,
    religion_description: string,
    political_leaning: string,
    political_description: string,
}